### ISSUE TITLE
Upload image one by one not showing image

### ISSUE THREAD

**Issue by ilhamjulianto** [TPMinan/react-upload-gallery#6]
![Screen Shot 2019-06-26 at 11 00 16](https://user-images.githubusercontent.com/40849246/60150171-b88abc80-9801-11e9-8b5a-bed2f70cecb7.png)

How can I upload image one by one without lost image

**Comment by TPMinan** [comment]
Sorry, i don't know exactly what you mean. Do you want to remove the wrong downloads? Or do you want to upload a single image?

**Comment by ilhamjulianto** [comment]
I want to upload a single image

**Comment by TPMinan** [comment]
The main purpose of the package is to upload multiple images. but you know limiting the number of pictures if you want. Like this.
```
<RUG
  rules={{
    limit: 10
  }}
/>
```

**Comment by ilhamjulianto** [comment]
sorry I want to upload images, when I upload one picture, the card displays the image, but for the second time, the card does not display the image
